# Generated by Django 5.2 on 2025-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_headline', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
