# Generated by Django 5.2 on 2025-10-12 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=200)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(default='1.0', max_length=10)),
            ],
        ),
    ]
