# Generated by Django 5.2 on 2025-04-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alter_about_this_organization_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('contact_whatsapp', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('elevation_start', models.CharField(blank=True, max_length=50, null=True)),
                ('elevation_end', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('hiking_time', models.CharField(blank=True, max_length=50, null=True)),
                ('habitat', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='travello.tour')),
            ],
        ),
    ]
