# Generated by Django 5.2 on 2025-10-13 00:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
