# Generated by Django 5.2 on 2025-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_tour_tourday'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('Beach', 'Beach'), ('Hiking', 'Hiking'), ('Safari', 'Safari'), ('Cultural', 'Cultural'), ('Kilimanjaro', 'Kilimanjaro')], max_length=100, null=True),
        ),
    ]
