# Generated by Django 5.2 on 2025-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_alter_termsandconditions_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountMeruSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.CharField(blank=True, max_length=255, null=True)),
                ('image3', models.CharField(blank=True, max_length=255, null=True)),
                ('image4', models.CharField(blank=True, max_length=255, null=True)),
                ('image5', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
