# Generated by Django 5.2 on 2025-04-24 14:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_tour_tour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
