# Generated by Django 5.2 on 2025-04-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_alter_tour_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='contact_whatsapp',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='website',
        ),
    ]
