# Generated by Django 5.2 on 2025-04-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_remove_tour_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourDay',
            new_name='Tour_Itinerary',
        ),
    ]
